### ISSUE TITLE
NoSuchMethodError: com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReaderSpi in Android studio,UBUNTU

### ISSUE THREAD

**Issue by sharon-joshi** [haraldk/TwelveMonkeys#511]
it was working fine with android 3.4.1. when i update it to 3.5.3 this error shown . please help. now i cant configure any logo or icon into the project 

```
java.lang.NoSuchMethodError: com.twelvemonkeys.imageio.plugins.tiff.TIFFImageReaderSpi.canDecodeAs(Ljava/lang/Object;I)Z
    at com.twelvemonkeys.imageio.plugins.tiff.BigTIFFImageReaderSpi.canDecodeInput(BigTIFFImageReaderSpi.java:58)
    at javax.imageio.ImageIO$CanDecodeInputFilter.filter(ImageIO.java:567)
    at javax.imageio.spi.FilterIterator.advance(ServiceRegistry.java:834)
    at javax.imageio.spi.FilterIterator.<init>(ServiceRegistry.java:828)
    at javax.imageio.spi.ServiceRegistry.getServiceProviders(ServiceRegistry.java:519)
    at javax.imageio.ImageIO.getImageReaders(ImageIO.java:646)
    at com.intellij.ide.util.TipUIUtil.read(TipUIUtil.java:254)
    at com.intellij.ide.util.TipUIUtil.updateImages(TipUIUtil.java:210)
    at com.intellij.ide.util.TipUIUtil.getTipText(TipUIUtil.java:126)
    at com.intellij.ide.util.TipUIUtil.openTipInBrowser(TipUIUtil.java:150)
    at com.intellij.ide.util.TipPanel.setTip(TipPanel.java:84)
    at com.intellij.ide.util.TipPanel.nextTip(TipPanel.java:107)
    at com.intellij.ide.util.TipDialog.initialize(TipDialog.java:55)
    at com.intellij.ide.util.TipDialog.<init>(TipDialog.java:46)
    at com.intellij.ide.util.TipDialog.createForProject(TipDialog.java:108)
    at com.intellij.ide.util.TipDialog.showForProject(TipDialog.java:95)
    at com.intellij.ide.TipOfTheDayStartupActivity.runImpl(TipOfTheDayStartupActivity.java:50)
    at com.intellij.ide.TipOfTheDayStartupActivity.lambda$runImpl$0(TipOfTheDayStartupActivity.java:46)
    at com.intellij.openapi.wm.impl.commands.InvokeLaterCmd.lambda$run$0(InvokeLaterCmd.java:37)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
    at java.awt.EventQueue.access$500(EventQueue.java:98)
    at java.awt.EventQueue$3.run(EventQueue.java:715)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
    at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:757)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:706)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:375)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by haraldk** [comment]
Hi Sharon,

As I understand from the stack trace, this is a stack trace from inside AndroidStudio?

I am not involved with the development JetBrains/IntelliJ or Google/AndroidStudio in any way (other than that I use their tools myself). You need to raise the issue with them.

I can assure you that the method in the stack trace does indeed exist, so I don't really understand what is going on here. Do you know what versions of the TwelveMonkeys library is bundled with the different versions of Android Studio?


Best regards,

-- 
Harald K

**Comment by haraldk** [comment]
Update: Seems to be a [known bug](https://youtrack.jetbrains.com/issue/MPS-30019). Most likely caused by a duplicate dependency/library with different versions. 

Closing this for now, feel free to report the issue to Android Studio, or comment on the JetBrains ticket if you have additional info.

-- 
Harald K
